WIP
bettermarks/license-manager-POC pull request #37
Opened 2023-03-09 18:04 UTC by cl3m0

still a lot to do :(

2023-03-13 16:10 UTC, rschach1 approved these changes
OK, ich brauch da morgen nochmal ein paar Erklärungen. Aber lass uns mal läänden

2023-03-13 16:14 UTC, saurabh2590 commented on k8s/lib/charts/migration-job.ts
> +    // Ideally we should not create same config map again
Change request: this comment is misleading and wrong copy paste.

2023-03-13 16:14 UTC, saurabh2590 requested changes
A tiny offending comment that threw me off.

2023-03-14 12:01 UTC, saurabh2590 approved these changes
Looks good to me.

2023-03-14 12:09 UTC, merged